In [1]:
!pip install numpy

In [2]:
import numpy as np

### **How check the version of numpy**

In [3]:
np.__version__

'2.5.2'

**syntax to create a numpy array** 
`np.array(value)`

In [14]:
arr2 = np.array([10,20,30,40,50,60])
arr2

array([10, 20, 30, 40, 50, 60])

**int, float, complex, bool, str** : These are  values, When passed to an array, they create a 0-dimensional array containing just that one value.

**set, dict** : NumPy does not unpack these. It treats the entire dictionary or set as a single "object".

In [22]:
np.array(10)
np.array(10.234)
np.array(20+3j)
np.array(True)
np.array('hello')
np.array({1,3,334546.46,5,7,567})
np.array({1:2, 3:4})


array({1: 2, 3: 4}, dtype=object)

**list, tuple** : These are naturally unpacked by NumPy to create a standard, multi-dimension array (e.g., 1D, 2D arrays)

In [18]:
np.array([1,2,3,4,56])
np.array((1,2,3,4,56))
np.array(['hi', 'hello'])

array(['hi', 'hello'], dtype='<U5')

In [24]:
np.array([1,2,3,4,{1}])
# np.array(['hello', {1}, ()]) #error 

array([1, 2, 3, 4, {1}], dtype=object)

If you create a NumPy array with heterogeneous (mixed) data types, NumPy automatically converts all elements into a homogeneous data type. 
It determines the final data type by following a strict upcasting hierarchy (priority list):

- bool (Lowest priority)
- int
- float
- complex
- str (String)
- object (set, dict, custom classes) (Highest priority)

In [39]:
np.array([True, False,])

array([ True, False])

In [40]:
np.array([1,2,3, True, False])

array([1, 2, 3, 1, 0])

In [41]:
np.array([1, 2.234, 12,  13.2, True, False])

array([ 1.   ,  2.234, 12.   , 13.2  ,  1.   ,  0.   ])

In [42]:
np.array([1, 2, 12,  (13+ 2j) , True, False])

array([ 1.+0.j,  2.+0.j, 12.+0.j, 13.+2.j,  1.+0.j,  0.+0.j])

In [45]:
np.array(['hello',1,2,4, 10j, 34.45])

array(['hello', '1', '2', '4', '10j', '34.45'], dtype='<U64')

In [44]:
np.array(['hello',1,2,4, 10j, 34.45, {122:4}, {1,23}])

array(['hello', 1, 2, 4, 10j, 34.45, {122: 4}, {1, 23}], dtype=object)

# Types of arrays:
1) zero-dimensional array (0D)

In [ ]:
np.array(10) #0D array

array(10)

2) Uni-dimensional array (1D)

In [ ]:
np.array((1,23,4,34,23,46,57,6,43)) #1D array
np.array([123,4,4,6,75]) #1D array

1

3) Bi-dimensional array (2D)

In [56]:
np.array([[1,2,4],
          [3,5,45]]) #2D array

array([[ 1,  2,  4],
       [ 3,  5, 45]])

In [58]:
# np.array([[1,2,3],
#           [1,23]]) # ValueError :- because the size of first element is not same as second

4) Multi-dimensional array (nD)

In [64]:
np.array([[[ 1,  2,  3],
           [ 1, 23, 34]],
           
          [[ 1,  2,  3],
           [ 1, 23, 34]]])

array([[[ 1,  2,  3],
        [ 1, 23, 34]],

       [[ 1,  2,  3],
        [ 1, 23, 34]]])