In [1]:
import numpy as np

In [10]:
arr1 = np.random.randint(10, 100,12)
arr2 = np.random.randint(1, 1000,20).reshape((2,10))
arr3 = arr2.reshape((2,2,5))

In [17]:
arrx = arr1
arrx

array([73, 20, 32, 89, 54, 35, 76, 38, 69, 75, 31, 50], dtype=int32)

In [19]:
arrx[10] = 1000
arrx

array([  73,   20,   32,   89,   54,   35,   76,   38,   69,   75, 1000,
         50], dtype=int32)

In [20]:
arr1

array([  73,   20,   32,   89,   54,   35,   76,   38,   69,   75, 1000,
         50], dtype=int32)

**Copy** → modification will not affect both arrays.<br>
`syntax : arr.copy()`

In [23]:
arrx = arr1.copy()
arrx[2] = 300
arrx

array([  73,   20,  300,   89,   54,   35,   76,   38,   69,   75, 1000,
         50], dtype=int32)

In [24]:
arr1

array([  73,   20,   32,   89,   54,   35,   76,   38,   69,   75, 1000,
         50], dtype=int32)

In [30]:
arr2x = arr2.copy()
arr2x[1][1]  = 2000
arr2x

array([[ 440,  671,  922,  654,  999,  198,  387,   11,  891,  874],
       [ 250, 2000,    7,  515,    9,  738,  654,  995,  817,  200]],
      dtype=int32)

In [31]:
arr2

array([[440, 671, 922, 654, 999, 198, 387,  11, 891, 874],
       [250, 279,   7, 515,   9, 738, 654, 995, 817, 200]], dtype=int32)

In [33]:
print(id(arr2))
print(id(arr2x))

2233925256368
2233925768400


**view** → if modification will affect both arrays but address will be different<br>
`syntax : arr.view()`

In [35]:
arrx = arr1.view()
print(id(arrx))
print(id(arr1))

2233925771760
2233925256080


In [37]:
arr1[3] = 100
arr1

array([  73,   20,   32,  100,   54,   35,   76,   38,   69,   75, 1000,
         50], dtype=int32)

In [38]:
arrx

array([  73,   20,   32,  100,   54,   35,   76,   38,   69,   75, 1000,
         50], dtype=int32)

1. np.min(arr)

In [ ]:
np.min(arr1)
np.min(arr2)
np.min(arr3)

np.int32(20)

2. np.max(arr)

In [55]:
np.max(arr1)
np.max(arr2)
np.max(arr3)

np.int32(999)

3. np.mean(arr)

In [59]:
np.mean(arr1)
np.mean(arr2)
np.mean(arr3)

np.float64(525.55)

4. np.median(arr)

In [63]:
arr2

array([[440, 671, 922, 654, 999, 198, 387,  11, 891, 874],
       [250, 279,   7, 515,   9, 738, 654, 995, 817, 200]], dtype=int32)

In [70]:
np.median(arr1)
np.median(arr2)
np.median(arr3)

np.float64(584.5)

In [68]:
arr = np.random.randint(1,100, 11)
arr

array([98, 36, 80, 68, 20, 12, 81, 68, 46, 38, 17], dtype=int32)

In [69]:
np.median(arr)

np.float64(46.0)

In [77]:
arr2

array([[440, 671, 922, 654, 999, 198, 387,  11, 891, 874],
       [250, 279,   7, 515,   9, 738, 654, 995, 817, 200]], dtype=int32)

5. np.std(arr)

In [76]:
np.std(arr1)
np.std(arr2)

np.float64(333.0170378524198)

6. np.var(arr)

In [82]:
np.var(arr2)

np.float64(110900.34749999999)

7. np.sum(arr)

In [84]:
np.sum(arr1)
np.sum(arr2)

np.int64(10511)

8. abs(arr)

In [90]:
arr = np.random.randint(-100, -1, 12)

In [88]:
abs(arr)

array([ 44,  91,  36,  95,  55,   3,  79,  93,  15,  37, 100,  12],
      dtype=int32)

In [89]:
arr

array([ -44,  -91,  -36,  -95,  -55,   -3,  -79,  -93,  -15,  -37, -100,
        -12], dtype=int32)

9. np.size(arr)

In [105]:
arr2x = np.random.rand(18) *100
arr2x[4] = np.nan
arr2x

array([85.29102596, 56.67743274, 95.87420711, 98.66120918,         nan,
        0.58859221, 39.71195684, 46.01605601, 33.58574918,  8.26155362,
       58.47149259,  3.82747452, 42.21727157, 28.41269061, 48.89335835,
        8.12517231, 93.21603968, 20.57107169])

In [ ]:
np.size(arr1)
np.size(arr2)
np.size(arr3)
np.size(arr)
np.size(arr2x)

18

10. np.sqrt(arr)

In [107]:
np.sqrt(arr1)
np.sqrt(25)

np.float64(5.0)

In [39]:
dict(np.random.randint(1,10, 10).reshape((5,2)))

{np.int32(2): np.int32(6),
 np.int32(1): np.int32(6),
 np.int32(8): np.int32(8),
 np.int32(3): np.int32(2)}

In [44]:
arr = np.random.randint(1,100,10).reshape((5,2))
a = map(lambda x : (int(x[0]), int(x[1])) ,arr)
list(arr)
list(a)

[(76, 38), (59, 32), (1, 75), (58, 2), (56, 26)]