In [1]:
import numpy as np

# Item Assignment

**`syntax :- variable[index] = new value`**

In [22]:
arr = np.array([1,3,45])
arr[-1] = 30
arr[0] = '10'
# arr[0] = 'hello' #error
# arr[1] = {1,3,54,4} #error 
arr


array([10,  3, 30])

In [23]:
arr2 = np.array([[13, 455, 46, 678],
                 [4565, 457,456, 688,]])

arr2[0] = 30 
arr2[1] = [3,4,5,5]
arr2

array([[30, 30, 30, 30],
       [ 3,  4,  5,  5]])

In [ ]:
# arr2[0] = [1,3,5] #error :- array from shape (3,) into shape (4,) is not possible
arr2[0] = [1]
arr2

array([[1, 1, 1, 1],
       [3, 4, 5, 5]])

In [19]:
arr3 = np.array([[[1,2,3],
                  [1,4,5],
                  [989,7,56]],

                 [[56,45,6],
                  [76,89,0],
                  [8,8,890]],

                 [[8,7,65],
                  [234,56, 76],
                  [3,5,6]]])

arr3[1][0][1] = '10'
# arr3[1][0][1] = 'hello' error because the data cannot be type casted
arr3

array([[[  1,   2,   3],
        [  1,   4,   5],
        [989,   7,  56]],

       [[ 56,  10,   6],
        [ 76,  89,   0],
        [  8,   8, 890]],

       [[  8,   7,  65],
        [234,  56,  76],
        [  3,   5,   6]]])

In [16]:
arr3[1] = 100
arr3

array([[[  1,   2,   3],
        [  1,   4,   5],
        [989,   7,  56]],

       [[100, 100, 100],
        [100, 100, 100],
        [100, 100, 100]],

       [[  8,   7,  65],
        [234,  56,  76],
        [  3,   5,   6]]])

In [17]:
arr3[1][1][1] = 0
arr3

array([[[  1,   2,   3],
        [  1,   4,   5],
        [989,   7,  56]],

       [[100, 100, 100],
        [100,   0, 100],
        [100, 100, 100]],

       [[  8,   7,  65],
        [234,  56,  76],
        [  3,   5,   6]]])

In [18]:
arr3[1] = [[13, 4, 5],
           [1, 45, 77],
           [34, 56, 76]]
arr3

array([[[  1,   2,   3],
        [  1,   4,   5],
        [989,   7,  56]],

       [[ 13,   4,   5],
        [  1,  45,  77],
        [ 34,  56,  76]],

       [[  8,   7,  65],
        [234,  56,  76],
        [  3,   5,   6]]])

# Slicing

### 1D array <hr>

**`syntax:- variable[start index : end index : step]`**

In [26]:
arr1 = np.array([1,2,3,4,5,67,34,46,57,6,8])

In [39]:
arr1[1:4:1]
arr1[ -1: 0: 1] #array([], dtype=int64)
arr1[ 0: 10: -1] #array([], dtype=int64)
arr1[ 2: 7 : -1] #array([], dtype=int64)
# arr1[::0]# error : step cannot be zero
arr1[::-1] #array([ 8,  6, 57, 46, 34, 67,  5,  4,  3,  2,  1])
arr1[4:100:3] #array([ 5, 46,  8])

array([ 5, 46,  8])

### 2D array <hr>

`syntax: variable[ (row slice) , (column slice) ]`  <br> or <br>
`variable[start :end :step,  start  : end  : step ]`

In [44]:
arr2 = np.array([[1,13,3,4],
                 [4,5,67,6],
                 [134,45,6,8]])
arr2[0:2:1 , 0:1:1]

array([[1],
       [4]])