In [1]:
import numpy as np

# Fancy Indexing<hr>
"Fancy slicing" more commonly known as fancy indexing in NumPy. Its a technique where you pass a list or another NumPy array of integers to select multiple specific elements from an array at once

`syntax : variable[collection]` 

But the collection should be list
In this the collection should have  a integer only  values

In [15]:
arr = np.array([1,2,3,4,5,6])
arr[[3,1,5]]

array([4, 2, 6])

In [23]:
arr2 = np.array([[1,2,34],
                 [76,54,3],
                 [3,45,345]])

arr2[[0,2,1]]

array([[  1,   2,  34],
       [  3,  45, 345],
       [ 76,  54,   3]])

In [29]:
arr3 = np.array([[[  1,   2,  34],
                  [  3,  45, 345],
                  [ 76,  54,   3]],

                 [[ 11,  142, 134],
                  [ 23,  425, 345],
                  [ 76,  524, 233]],

                 [[ 156,  5,  4],
                  [   3,  4,  4],
                  [ 786, 56, 54]]])

arr3[[2,0,2]]


array([[[156,   5,   4],
        [  3,   4,   4],
        [786,  56,  54]],

       [[  1,   2,  34],
        [  3,  45, 345],
        [ 76,  54,   3]],

       [[156,   5,   4],
        [  3,   4,   4],
        [786,  56,  54]]])