In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5,12,6])

arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

# Operations on array <hr>

### Addition 

In [ ]:
# arr1 = np.array([1,2,3,4,5,12,6])
arr1 + 10 # array([11, 12, 13, 14, 15, 22, 16]) 

np.array(['hello', 'hi']) + ' world' # array(['hello world', 'hi world'], dtype='<U11')

arr1 + np.array([ 9, 8, 7, 6, 5, 4, 3]) #array([10, 10, 10, 10, 10, 16,  9])

# arr1 + np.array([ 9, 8, 7, 6, 5]) # Error because shape of both the array is different

# arr1 + np.array([1,2,34,3,4,'hi', 7]) # Error because the dtype of 
                                        # both the array doent support addition

array([10, 10, 10, 10, 10, 16,  9])

In [ ]:
# arr2 = np.array([   [ 1,  2,  3,  4],
#                     [ 5,  6,  7,  8],
#                     [ 9, 10, 11, 12],
#                     [13, 14, 15, 16]])

arr2 + 10
'''array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26]])'''


arr2 + np.array([[  1,   2,  34 , 2344],
                 [  3,  45, 345, 456],
                 [ 76,  54,   3, 4],
                 [123, 24, 5,  46]],)
'''array([[   2,    4,   37, 2348],
       [   8,   51,  352,  464],
       [  85,   64,   14,   16],
       [ 136,   38,   20,   62]])'''


# arr2 + np.array([[  1,   2,  34 , 2344],
#                  [  3,  'hi', 345, 456],
#                  [ 76,  54,   3, 4],
#                  [123, 24, 5,  'hello']],)  # Error because the dtype of 
                                              # both the array doent support addition

array([[   2,    4,   37, 2348],
       [   8,   51,  352,  464],
       [  85,   64,   14,   16],
       [ 136,   38,   20,   62]])

### Substraction

In [13]:
# arr1 = np.array([ 1,  2,  3,  4,  5, 12,  6])
arr1 - 10

arr1 - [12,32,43,33,4,323,55]
arr1 - (12,32,43,33,4,323,55)

arr1 - np.array([12,13,4,5,4,6,3])

# arr1 - np.array([12,13,6,3]) #error because shape is diff
# arr1 - np.array([12,13,4,5,4,'hello',3]) #error dtype not supported


array([-11, -11,  -1,  -1,   1,   6,   3])

### multiplication

In [19]:
# arr1 = np.array([ 1,  2,  3,  4,  5, 12,  6])

arr1 * 10

arr1 * np.array([1,2,34,4,5,24,3])

# np.array(['hello', 'hi']) * 10 # Error
# np.array(['hello', 'hi']) * np.array(['hello', 'world']) # error dtype not support

# np.array(['hello', 'hi']) * np.array([1,2]) # error dtype not support

array([  1,   4, 102,  16,  25, 288,  18])

In [20]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [23]:
np.array([[ 1,  2,  3],
        [ 5,  6,  7]]) * np.array([[  1,   2,  34 ],
                                    [  3,  45, 345]],)

array([[   1,    4,  102],
       [  15,  270, 2415]])

## looping on array

In [24]:
for i in arr1:
    print(i)

1
2
3
4
5
12
6


In [28]:
for i in arr2:
    print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]
