In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5,12,6,452,2,3455,54,4,435,8,986,56,4,534,32,456,])

arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

In [5]:
arr1.shape
arr2.shape

(4, 4)

## Methods of array <hr>

**reshape** → To change the dimension of array. <br>
`syntax : array.reshape(row, column)`

In [10]:
arr1.reshape(2,10)
# arr1.reshape(2,15) # Error : the product of row and column is not equals to the number
                             # of elements

array([[   1,    2,    3,    4,    5,   12,    6,  452,    2, 3455],
       [  54,    4,  435,    8,  986,   56,    4,  534,   32,  456]])

3d array
`syntax:array.reshape(depth,row, column)`

In [17]:
arr2.reshape(2,8)
# arr2 # original didnt get modified 
# arr2.reshape(1.6, 10 ) #error cannot be a float
arr2.reshape(2,2,4)
arr2.reshape(16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

**arange** → Used to create array between specified range. We can generate float values also. <br>
`syntax : np.arange(start, end+1, step)`

In [26]:
arr1 = np.arange(20, 100, 3)
arr1

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68,
       71, 74, 77, 80, 83, 86, 89, 92, 95, 98])

In [27]:
arr2 = np.arange(0,9).reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

<p>arange with float</p>

In [35]:
arr3 = np.arange(0,10.23, 0.5)
arr3

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

**linspace** → Create an array with equally spaced values. By default create an array with 50 values. <br>
`Syntax: np.linspace(start, end, number of values)`

In [40]:
np.linspace(1, 100, 9)

array([  1.   ,  13.375,  25.75 ,  38.125,  50.5  ,  62.875,  75.25 ,
        87.625, 100.   ])

In [53]:
np.linspace(1, 50)
np.linspace(1, 50).reshape(5, 10)

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.],
       [31., 32., 33., 34., 35., 36., 37., 38., 39., 40.],
       [41., 42., 43., 44., 45., 46., 47., 48., 49., 50.]])

**zeros** → Used to create array with zeros. <br>
`Syntax: 1D → np.zeros(n)`
`2D → np.zeros((r, c))`

In [57]:
arr1 = np.zeros(5)
arr1

array([0., 0., 0., 0., 0.])

In [64]:
arr2 = np.zeros((2,5))
arr2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [62]:
arr3 = np.zeros((3,3,3))
arr3

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

**ones** → Used to create array filled with ones.<br>
`syntax: 1D → np.ones(n)`
`2D → np.ones((r, c))`


In [65]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [67]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [68]:
np.ones((2, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

**Identity**→ used to create identity matrix<br>
Rules of identity matrix: rows = columns , primary diagonal should be 1 <br>
`syntax : np.identity(n)` 



In [75]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
arr1 = np.identity(3, dtype=int)
arr1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [74]:
arr1.dtype

dtype('int64')

**random.randint** → It is used to create array with random values within the
specified limit. It will only generate integer values. <br>
`syntax: np.random.randint(start, end+1, no of values)`

In [83]:
np.random.randint(1, 100, 10)

array([41, 61, 83, 44, 20, 96, 84,  9, 96, 38], dtype=int32)

In [ ]:
np.random.randint(2,1000, 3000)

array([404, 183, 305, ..., 589, 497, 400], shape=(3000,), dtype=int32)

In [87]:
np.random.randint(2,10, 6).reshape((2,3))

array([[7, 7, 9],
       [7, 5, 3]], dtype=int32)

**random.rand** → It is used to create an array with positive values b/w 0 to 1 only (exclusive).<br>
`syntax:np.random.rand(n)`

In [123]:
np.random.rand()

0.26870833932050064

In [127]:
np.random.rand(2)

array([0.83394414, 0.87859598])

In [122]:
np.random.rand(10) * 100

array([50.5874802 ,  2.73674473, 30.30075695, 46.7652509 , 83.06302867,
       67.32157421, 33.68357127, 88.09274096, 46.02849854, 17.83077345])